# Generated by Django 4.1.4 on 2023-01-04 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('gen_id', models.AutoField(primary_key=True, serialize=False)),
                ('gen_genero', models.CharField(max_length=20, verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('mid_id', models.AutoField(primary_key=True, serialize=False)),
                ('mid_midia', models.CharField(max_length=20, verbose_name='Mídia')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('obr_id', models.AutoField(primary_key=True, serialize=False)),
                ('obr_titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('obr_sinopse', models.CharField(max_length=500, verbose_name='Sinopse')),
                ('obr_data', models.DateField(verbose_name='Data de Lançamento')),
                ('obr_producao', models.TextField(verbose_name='Lista de Produtores')),
                ('obr_capa', models.CharField(max_length=500, verbose_name='Link da Capa')),
                ('obr_classificacao', models.CharField(choices=[('L', 'L'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18')], default='L', max_length=2, verbose_name='Classificação Etária')),
                ('obr_gen_genero', models.ManyToManyField(to='Show.genero', verbose_name='Gêneros')),
                ('obr_mid_midia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.midia', verbose_name='Mídia')),
            ],
        ),
    ]
