# Generated by Django 4.1.4 on 2022-12-30 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('fun_id', models.AutoField(primary_key=True, serialize=False)),
                ('fun_funcao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('gen_id', models.AutoField(primary_key=True, serialize=False)),
                ('gen_genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('tip_id', models.AutoField(primary_key=True, serialize=False)),
                ('tip_tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_funcao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.funcao')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('obr_id', models.AutoField(primary_key=True, serialize=False)),
                ('obr_titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('obr_sinopse', models.CharField(max_length=500, verbose_name='Sinopse')),
                ('obr_genero', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.genero')),
                ('obr_producao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.producao')),
                ('obr_tipo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.tipo')),
            ],
        ),
    ]
