# Generated by Django 4.1.4 on 2023-01-01 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('fuc_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuc_funcao', models.CharField(blank=True, max_length=50, verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('fun_id', models.AutoField(primary_key=True, serialize=False)),
                ('fun_nome', models.CharField(blank=True, max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('gen_id', models.AutoField(primary_key=True, serialize=False)),
                ('gen_genero', models.CharField(max_length=20, verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('mid_id', models.AutoField(primary_key=True, serialize=False)),
                ('mid_midia', models.CharField(max_length=20, verbose_name='Mídia')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('obr_id', models.AutoField(primary_key=True, serialize=False)),
                ('obr_titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('obr_sinopse', models.CharField(max_length=500, verbose_name='Sinopse')),
                ('obr_data', models.DateField(verbose_name='Data de Lançamento')),
                ('obr_classificacao', models.CharField(choices=[('L', 'L'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18')], default='L', max_length=2, verbose_name='Classificação Etária')),
                ('obr_mid_midia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.midia', verbose_name='Mídia')),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_fuc_funcao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.funcao', verbose_name='Função')),
                ('pro_fun_funcionario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.funcionario', verbose_name='Funcionário')),
                ('pro_obr_obra', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Produção',
                'verbose_name_plural': 'Produtores',
            },
        ),
        migrations.CreateModel(
            name='Genero_da_Obra',
            fields=[
                ('geo_id', models.AutoField(primary_key=True, serialize=False)),
                ('geo_gen_genero', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.genero', verbose_name='Gênero')),
                ('geo_obr_obra', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Gênero da Obra',
                'verbose_name_plural': 'Gêneros da Obra',
            },
        ),
    ]
