# Generated by Django 4.1 on 2022-12-31 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0002_alter_obra_obr_classificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero_da_obra',
            options={'verbose_name': 'Gênero', 'verbose_name_plural': 'Gêneros'},
        ),
        migrations.AlterField(
            model_name='genero_da_obra',
            name='geo_gen_genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.genero', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='genero_da_obra',
            name='geo_obr_obra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.obra', verbose_name='Obra'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obr_mid_mídia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.midia', verbose_name='Mídia'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='pro_fuc_funcao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.funcao', verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='pro_fun_funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='pro_obr_obra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.obra', verbose_name='Obra'),
        ),
    ]
