# Generated by Django 4.1 on 2022-12-31 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Show', '0003_alter_genero_da_obra_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obras_do_Usuario',
            fields=[
                ('odu_id', models.AutoField(primary_key=True, serialize=False)),
                ('odu_obr_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.obra', verbose_name='Obra')),
                ('odu_use_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
