# Generated by Django 4.1.4 on 2023-01-01 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Show', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistido',
            fields=[
                ('ass_id', models.AutoField(primary_key=True, serialize=False)),
                ('ass_obr_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.obra', verbose_name='Obra')),
                ('ass_use_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Obra Assistida',
                'verbose_name_plural': 'Obras Assistidas',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rev_id', models.AutoField(primary_key=True, serialize=False)),
                ('rev_review', models.CharField(max_length=1000, verbose_name='Review')),
                ('rev_classificacao', models.CharField(choices=[('1', 'Estrela 1'), ('2', 'Estrela 2'), ('3', 'Estrela 3'), ('4', 'Estrela 4'), ('5', 'Estrela 5')], max_length=1, verbose_name='Classificação')),
                ('rev_ass_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.assistido', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
