# Generated by Django 4.1.4 on 2023-01-04 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Show', '0002_alter_obra_obr_sinopse'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rev_ass_id',
        ),
        migrations.AddField(
            model_name='review',
            name='rev_obr_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Show.obra', verbose_name='Obra'),
        ),
        migrations.AddField(
            model_name='review',
            name='rev_use_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rev_classificacao',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rev_review',
            field=models.TextField(verbose_name='Review'),
        ),
        migrations.DeleteModel(
            name='Assistido',
        ),
    ]
